print(" ------------------------------------------------")
print("|                                                |")
print("|    04GoodTeacher                               |")
print("|    Name : Natalie                              |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
name = input("Teacher's name (try Mr Horan) ")
print(name + " is an ok teacher")
