print(" ------------------------------------------------")
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Natalie                              |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")